#!/usr/bin/env bash
# configure web-02 to be identical to web-01.

sudo apt update
sudo apt install -y nginx
server_hostname=$(hostname)
cat <<EOL | sudo tee /etc/nginx/sites-available/default
server {
    listen 80 default_server;
    listen [::]:80 default_server;

    server_name _;

    add_header X-Served-By $server_hostname;

    location / {
        # Your existing configuration for handling requests goes here
        # For example, you can proxy_pass to your application server or serve static files.
        # This will vary depending on your specific setup.
        # Example: proxy_pass http://localhost:8000;
    }
}
EOL

sudo ln -s /etc/nginx/sites-available/default /etc/nginx/sites-enabled/

sudo nginx -t

sudo systemctl reload nginx
