#!/usr/bin/env bash
# install load balancer
sudo apt update -y
sudo apt install haproxy -y
echo 'ENABLED=1' | sudo tee -a /etc/default/haproxy
printf %s 'frontend haproxy_balancer
    bind *:80
    mode http
    default_backend webservers
backend webservers
    balance roundrobin
    server 5668-web-01 52.91.38.203:80  check
    server 5668-web-02 3.83.231.146:80 check

' | sudo tee -a /etc/haproxy/haproxy.cfg
sudo service haproxy restart
