#!/usr/bin/env bash
# Transfers a file from a client to a server.
if [ $# -lt 3 ];
then
   echo"Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY";
   exit;
fi;

if [$# -ge 4 ];
then
   scp -o StrictHostKeyChecking=0 -i "$4" "$1" "$3"@"$2":~/
else
   scp -o StrictHostKeyChecking=0 "$1" "$3"@"$2":~/
fi;
