#!/usr/bin/env bash
# Configure nginx server redirecting to another page

sudo apt-get update
sudo apt-get -y install nginx

cp /var/www/html/index.nginx-debian.html /var/www/html/index.nginx-debian.html.bckp

echo "Hello World!" | sudo tee /var/www/html/index/html

string_for_replacement="server_name _;\n\trewrite ^\/redirect_me https:\/\/github.com\/besthor permanent;"

sudo sed -i "s/server_name -;/$string_for_replacement/" /etc/nginx/sites-enabled/default

sudo service nginx restar
